import { 
  SiReact, 
  SiNextdotjs, 
  SiTypescript, 
  SiTailwindcss, 
  SiFramer,
  SiNodedotjs,
  SiExpress,
  SiJavascript,
  SiGit,
  SiFigma,
  SiMongodb,
  SiPostgresql,
  SiDocker,
  SiGraphql,
  SiRedux,
  SiSass,
  SiWebpack,
  SiVite,
  SiVercel,
  SiNetlify,
  SiStripe,
  SiTwilio,
  SiSocketdotio
} from 'react-icons/si';
import { FaHtml5, FaCss3Alt, FaPython, FaPhp, FaAws } from 'react-icons/fa';
import { Technology } from '../components/TechCard';

export const technologies: Technology[] = [
  { name: 'React', icon: SiReact, color: '#61DAFB' },
  { name: 'Next.js', icon: SiNextdotjs, color: '#000000' },
  { name: 'TypeScript', icon: SiTypescript, color: '#3178C6' },
  { name: 'JavaScript', icon: SiJavascript, color: '#F7DF1E' },
  { name: 'Tailwind CSS', icon: SiTailwindcss, color: '#06B6D4' },
  { name: 'Framer Motion', icon: SiFramer, color: '#0055FF' },
  { name: 'Node.js', icon: SiNodedotjs, color: '#339933' },
  { name: 'AWS', icon: FaAws, color: '#FF9900' },
  { name: 'Express.js', icon: SiExpress, color: '#000000' },
  { name: 'HTML5', icon: FaHtml5, color: '#E34F26' },
  { name: 'CSS3', icon: FaCss3Alt, color: '#1572B6' },
  { name: 'Git', icon: SiGit, color: '#F05032' },
  { name: 'Figma', icon: SiFigma, color: '#F24E1E' },
  { name: 'Redux', icon: SiRedux, color: '#764ABC' },
  { name: 'Sass', icon: SiSass, color: '#CC6699' },
  { name: 'Webpack', icon: SiWebpack, color: '#8DD6F9' },
  { name: 'Vercel', icon: SiVercel, color: '#000000' },
  { name: 'Netlify', icon: SiNetlify, color: '#00C7B7' },
  { name: 'Twilio', icon: SiTwilio, color: '#F22F46' },
];
